"""initial schema

Revision ID: 6ec9cb8af050
Revises: 
Create Date: 2026-06-08 18:55:35.502653

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6ec9cb8af050'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_ledger',
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('dedupe_key', sa.String(length=512), nullable=False),
    sa.Column('build_id', sa.String(length=64), nullable=False),
    sa.Column('lane', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('org_id', 'dedupe_key')
    )
    op.create_table('conversation_log',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('build_id', sa.String(length=64), nullable=False),
    sa.Column('dedupe_key', sa.String(length=512), nullable=False),
    sa.Column('lane', sa.String(length=16), nullable=False),
    sa.Column('harness', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('transcript_json', sa.Text(), nullable=False),
    sa.Column('files_changed_json', sa.Text(), nullable=False),
    sa.Column('usage_json', sa.Text(), nullable=True),
    sa.Column('stop_reason', sa.String(length=32), nullable=False),
    sa.Column('snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_log', schema=None) as batch_op:
        batch_op.create_index('ix_conversation_org_time', ['org_id', 'created_at'], unique=False)

    op.create_table('entity_baselines',
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('mean_gap', sa.Float(), nullable=False),
    sa.Column('m2_gap', sa.Float(), nullable=False),
    sa.Column('last_event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('org_id', 'subject', 'source_kind')
    )
    op.create_table('fs_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('build_id', sa.String(length=64), nullable=True),
    sa.Column('parent_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('ref', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fs_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_fs_snapshots_org_time', ['org_id', 'created_at'], unique=False)

    op.create_table('ingested_events',
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingest_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('org_id', 'event_id')
    )
    with op.batch_alter_table('ingested_events', schema=None) as batch_op:
        batch_op.create_index('ix_ingested_events_org_time', ['org_id', 'ingest_time'], unique=False)

    op.create_table('mcp_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_requests', schema=None) as batch_op:
        batch_op.create_index('ix_mcp_requests_org_time', ['org_id', 'created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_email', ['email'], unique=True)
        batch_op.create_index('ix_users_google_sub', ['google_sub'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('github_login', sa.String(length=255), nullable=True),
    sa.Column('github_token', sa.Text(), nullable=True),
    sa.Column('slack_team_id', sa.String(length=64), nullable=True),
    sa.Column('slack_team_name', sa.String(length=255), nullable=True),
    sa.Column('slack_token', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('secret', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cursor', sa.String(length=255), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources')
    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_google_sub')
        batch_op.drop_index('ix_users_email')

    op.drop_table('users')
    with op.batch_alter_table('mcp_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_mcp_requests_org_time')

    op.drop_table('mcp_requests')
    with op.batch_alter_table('ingested_events', schema=None) as batch_op:
        batch_op.drop_index('ix_ingested_events_org_time')

    op.drop_table('ingested_events')
    with op.batch_alter_table('fs_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_fs_snapshots_org_time')

    op.drop_table('fs_snapshots')
    op.drop_table('entity_baselines')
    with op.batch_alter_table('conversation_log', schema=None) as batch_op:
        batch_op.drop_index('ix_conversation_org_time')

    op.drop_table('conversation_log')
    op.drop_table('build_ledger')
    # ### end Alembic commands ###
